[package]
name = "raw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.crossterm]
version = "0.23"
features = ["event-stream"]

[dependencies.unicode-segmentation]
version = "1.9.0"